export const academies = [
  "AIX-MARSEILLE",
  "AMIENS",
  "BESANCON",
  "BORDEAUX",
  "CAEN",
  "CLERMONT-FERRAND",
  "CORSE",
  "CRETEIL",
  "DIJON",
  "GRENOBLE",
  "GUADELOUPE",
  "GUYANE",
  "LA REUNION",
  "LILLE",
  "LIMOGES",
  "LYON",
  "MARTINIQUE",
  "MAYOTTE",
  "MONTPELLIER",
  "NANCY-METZ",
  "NANTES",
  "NICE",
  "NORMANDIE",
  "ORLEANS-TOURS",
  "PARIS",
  "POITIERS",
  "REIMS",
  "RENNES",
  "ROUEN",
  "STRASBOURG",
  "TOULOUSE",
  "VERSAILLES",
];

export const rentree_scolaire = [
  "2016-2017",
  "2017-2018",
  "2018-2019",
  "2019-2020",
  "2020-2021",
  "2021-2022",
];

export const secteurs = [
  "public",
  "prive",
];

export const departements = [
  "AIN",
  "AISNE",
  "ALLIER",
  "ALPES-DE-HAUTE-PROVENCE",
  "ALPES-MARITIMES",
  "ARDECHE",
  "ARDENNES",
  "ARIEGE",
  "AUBE",
  "AUDE",
  "AVEYRON",
  "BAS-RHIN",
  "BOUCHES-DU-RHONE",
  "CALVADOS",
  "CANTAL",
  "CHARENTE",
  "CHARENTE-MARITIME",
  "CHER",
  "CORREZE",
  "CORSE-DU-SUD",
  "COTE D\'OR",
  "COTES D\'ARMOR",
  "CREUSE",
  "DEUX-SEVRES",
  "DORDOGNE",
  "DOUBS",
  "DROME",
  "ESSONNE",
  "EURE",
  "EURE-ET-LOIR",
  "FINISTERE",
  "GARD",
  "GERS",
  "GIRONDE",
  "GUADELOUPE",
  "GUYANE",
  "HAUT-RHIN",
  "HAUTE SAVOIE",
  "HAUTE-CORSE",
  "HAUTE-GARONNE",
  "HAUTE-LOIRE",
  "HAUTE-MARNE",
  "HAUTE-SAONE",
  "HAUTE-VIENNE",
  "HAUTES-ALPES",
  "HAUTES-PYRENEES",
  "HAUTS-DE-SEINE",
  "HERAULT",
  "ILLE-ET-VILAINE",
  "INDRE",
  "INDRE-ET-LOIRE",
  "ISERE",
  "JURA",
  "LA REUNION",
  "LANDES",
  "LOIR-ET-CHER",
  "LOIRE",
  "LOIRE-ATLANTIQUE",
  "LOIRET",
  "LOT",
  "LOT-ET-GARONNE",
  "LOZERE",
  "MAINE-ET-LOIRE",
  "MANCHE",
  "MARNE",
  "MARTINIQUE",
  "MAYENNE",
  "MAYOTTE",
  "MEURTHE-ET-MOSELLE",
  "MEUSE",
  "MORBIHAN",
  "MOSELLE",
  "NIEVRE",
  "NORD",
  "OISE",
  "ORNE",
  "PARIS",
  "PAS-DE-CALAIS",
  "PUY-DE-DOME",
  "PYRENEES-ATLANTIQUES",
  "PYRENEES-ORIENTALES",
  "RHONE",
  "SAONE-ET-LOIRE",
  "SARTHE",
  "SAVOIE",
  "SEINE MARITIME",
  "SEINE-ET-MARNE",
  "SEINE-SAINT-DENIS",
  "SOMME",
  "TARN",
  "TARN-ET-GARONNE",
  "TERRITOIRE DE BELFORT",
  "VAL-D'OISE",
  "VAL-DE-MARNE",
  "VAR",
  "VAUCLUSE",
  "VENDEE",
  "VIENNE",
  "VOSGES",
  "YONNE",
]

// Fonction d'assistance pour encoder les paramètres d'URL
export function encodeParam(key, value) {
  return `refine=${encodeURIComponent(key)}:${encodeURIComponent(value)}`;
}

export function getColorForIps(ips) {
  if (ips <= 70) return '#8B0000';
  else if (ips <= 80) return '#FF0000';
  else if (ips <= 90) return '#FF4500';
  else if (ips <= 100) return '#FFA500';
  else if (ips <= 110) return '#9ACD32';
  else if (ips <= 120) return '#7CFC00';
  else return '#32CD32'; // Pour 121 et plus
}
